### ISSUE TITLE
Would be great if we can show the full name of the thread :)

### ISSUE THREAD

**Issue by theapache64** [Grigory-Rylov/android-methods-profiler#103]
![image](https://github.com/Grigory-Rylov/android-methods-profiler/assets/9678279/f4202434-64df-476e-8722-9e1c1d279321)

**Comment by Grigory-Rylov** [comment]
Show full name when mouse is hovered on button?

**Comment by theapache64** [comment]
@Grigory-Rylov currently it shows "Open thread switcher", but that should also work. However, in my opinion, showing the full thread name would be better. Alternatively, you could consider increasing the maximum character limit slightly.
