### ISSUE TITLE
Can we show the sum total of all blocks?

### ISSUE THREAD

**Issue by theapache64** [Grigory-Rylov/android-methods-profiler#105]
![image](https://github.com/Grigory-Rylov/android-methods-profiler/assets/9678279/5510d058-d4a7-4b90-b342-728017db3270)

For example, here it currently shows the current block time. Can we show sum of those 20 blocks?

**Comment by Grigory-Rylov** [comment]
Good suggestion! Thanks!

**Comment by Grigory-Rylov** [comment]
<img width="603" alt="image" src="https://github.com/user-attachments/assets/1a304bb2-e922-45b4-bb65-569560ed6389">

Available from version 24.08.24.0
