### ISSUE TITLE
Restore support of the app

### ISSUE THREAD

**Issue by Monabr** [Grigory-Rylov/android-methods-profiler#108]
Hello. You have a great library!

Please restore support for the latest android studio as well as standalone app.

**Comment by Grigory-Rylov** [comment]
Done) You can get it in latest release https://github.com/Grigory-Rylov/android-methods-profiler/releases/tag/v24.07.31.0

Or you can wait until JetBrains approves update in plugin store

**Comment by Grigory-Rylov** [comment]
@Monabr Here you are ) https://github.com/Grigory-Rylov/android-methods-profiler/releases/download/v24.07.31.0/yamp-24.07.31.jar
