### ISSUE TITLE
Update the standalone app and make it easier to open.

### ISSUE THREAD

**Issue by Monabr** [Grigory-Rylov/android-methods-profiler#115]
Hello.

Please update `.jar` to the current version and make it possible to run without using the terminal.

**Comment by Grigory-Rylov** [comment]
Hello! Sorry for late answer ( You can get latest  desktop yamp jar with simpleperf format support in https://github.com/Grigory-Rylov/android-methods-profiler/releases/download/v24.08.23.0/yamp-24.08.23.jar
