### ISSUE TITLE
Magic Number mismatch

### ISSUE THREAD

**Issue by michaeltiket** [Grigory-Rylov/android-methods-profiler#74]
i have using latest version
I am tracing release version app using simplePref https://android.googlesource.com/platform/system/extras/+/master/simpleperf/doc/scripts_reference.md#app_profilerpy

when i open `.trace` file or `mapping.txt` file, to this error. 
![image](https://user-images.githubusercontent.com/73816230/135071691-9acfd739-7c64-4a84-8435-c642f184e024.png)

TraceFile and mapping.txt
[Archive.zip](https://github.com/Grigory-Rylov/android-methods-profiler/files/7243184/Archive.zip)

Am i missing something?

Thank you

**Comment by Grigory-Rylov** [comment]
Hello! Thanks for report! You sent tracing of C++ methods, but  YAMP does not yet supports C++ traces, only java method traces.

**Comment by michaeltiket** [comment]
> Hello! Thanks for report! You sent tracing of C++ methods, but YAMP does not yet supports C++ traces, only java method traces.

How about `mapping.txt`? because i got similar error

**Comment by Grigory-Rylov** [comment]
When you open `mapping.txt` after opening `.trace` before,  YAMP tries reopen last `.trace` file, a think it not critical bug.

If you want to record java methods tracing from release app, you can try to use YAMP with rooted android device. Or, if you have access to sources, you can record traces programmatically

**Comment by michaeltiket** [comment]
> you can try to use YAMP with rooted android device
ah need rooted device, noted!

before i tried to record but showing error need to close Android Studio, and after close it, and still have same error
![image](https://user-images.githubusercontent.com/73816230/135080339-24d86de4-0836-4c4b-8140-ca4423fcc8c4.png)

**Comment by Grigory-Rylov** [comment]
Did you try on rooted devices?

**Comment by michaeltiket** [comment]
not yet, doesn't have rooted device yet. i will reach back when i have it.

Thank you 🙏

**Comment by Grigory-Rylov** [comment]
If you have not rooted devices and has access to sources, you can get trace from release app by using this 2 step:

1) Start recording
https://github.com/Grishberg/simple-binary-preferences/blob/master/demo/src/main/java/com/github/grishberg/simplebinarypreferences/App.java#L14

2) Stop recording
https://github.com/Grishberg/simple-binary-preferences/blob/master/demo/src/main/java/com/github/grishberg/simplebinarypreferences/MainActivity.java#L103

For example I introduced build variable and when I build release app with new build parameter, I get trace recirding feature.

Also you can stop recording in some broadcast, then you need to send this broadcast from adb when you want to stop trace recording.

**Comment by michaeltiket** [comment]
ah using systrace, noted!
but i want to trace before the application, Maybe can have other workaround by call in `ContentProvider`
Just for learning about performance, relate to https://dev.to/pyricau/android-vitals-profiling-app-startup-32ek
i saw this cool tool because someone mentioned in the commend section

**Comment by Grigory-Rylov** [comment]
>ah using systrace
It's not systrace, it's `java method sample/trace` recording.

>but i want to trace before the application, Maybe can have other workaround by call in ContentProvider
Unfortunately, programmatically I was able to write only starting with Application.onCreate =(

**Comment by Grigory-Rylov** [comment]
>Just for learning about performance, relate to https://dev.to/pyricau/android-vitals-profiling-app-startup-32ek

It's very cool article!

**Comment by michaeltiket** [comment]
i tried on emulator AVD, its works because AVD is rooted, yeah i think i neee rooted device, thanks, 

and about `mapping.txt` will it deobfuscate the flamechart?

**Comment by michaeltiket** [comment]
Forget it, because the box in the flame chart too small, the text got shorten, i thought the deobfuscate not working, 
nice tools

**Comment by Grigory-Rylov** [comment]
Sorry for late answer, you can try to open SimplePerf traces since https://github.com/Grigory-Rylov/android-methods-profiler/releases/tag/v24.08.24.0
