### ISSUE TITLE
Open .trace file error - Magic number mismatch

### ISSUE THREAD

**Issue by theapache64** [Grigory-Rylov/android-methods-profiler#83]
![image](https://user-images.githubusercontent.com/9678279/182486842-e4e2ee7f-367d-4a69-8aef-abadb71af38b.png)

Can't open callstack `.trace` file created using Studio

**Comment by Grigory-Rylov** [comment]
Hello! Can you attach .trace file? Maybe it is native methods tracing? Native tracing not supported yet, only java methods tracing.

**Comment by Grigory-Rylov** [comment]
Thanks for issue, there are two different trace format : simplepref and perfetto that YAMP not yet supported (  For now only two  type from list : java/kotlin trace recording and java/kotlin sample recording (legacy)

<img width="415" alt="image" src="https://user-images.githubusercontent.com/25260420/182583758-b5f8942a-b2f3-4474-9bf2-4f5774f804c0.png">

I think need to support new trace formatы.

**Comment by pyricau** [comment]
Support for simpleperf format would be amazing, as it's a method of recording that has a much lower overhead than the old Java method tracing.

Perfetto is probably less important, as https://ui.perfetto.dev is already really fast and has a ton of features.

**Comment by Grigory-Rylov** [comment]
Added supporting simpleperf format, could you please try with new virsion? https://github.com/Grigory-Rylov/android-methods-profiler/releases/tag/v24.08.22.0
