### ISSUE TITLE
Can't find process

### ISSUE THREAD

**Issue by theapache64** [Grigory-Rylov/android-methods-profiler#87]
![image](https://user-images.githubusercontent.com/9678279/185536672-ef5941f9-8420-4955-9e20-83e38ab3455f.png)

After pressing the `Start` button, the app has started but am getting this dialogue. I don't have AndroidStudio opened btw. Any idea why this is happening ? Any workaround ?

**Comment by Grigory-Rylov** [comment]
Usually that happens when trying to profile release app on non rooted device. Have you tried YAMP plugin for Android Studio? It reuse AS' adb bridge and can work with opened AS instances. Also plugin is newer and can search methods in all threads.

**Comment by theapache64** [comment]
@Grigory-Rylov Ohh..No, I haven't. Standalone was working perfectly fine for me. Does the plugin support the release app on non-rooted devices?  Is there any other advantage to using the plugin, apart from method search?

**Comment by Grigory-Rylov** [comment]
Plugin not support release app profiling on non rooted device. Difference now only in multithreading searching. When I figure out the how to make fat-jar with Gradle 7, then I will update standalone YAMP)

If you want to profile your release app, you can record . trace profile programmatically by calling ’Debug.startMethodTracingSampling("tracing.trace", BUFFER_IN_BYTES, SAMPLING_IN_MICROSECONDS)’ and then you must call  ’Debug.stopMethodTracing();’ for stopping recording.
 
Then you must pull trace file from device.

But you can't successful record before App.onCreate() is called. https://github.com/Grishberg/simple-binary-preferences/blob/master/demo/src/main/java/com/github/grishberg/simplebinarypreferences/App.java#L14

**Comment by theapache64** [comment]
Cool. Thanks 👍
